services:
 db:
   image: postgres:16.3
   restart: always
   ports:
     - 5432:5432
   environment:
     POSTGRES_DB: park
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: 'root'
   volumes:
     - ./database:/var/lib/postgresql/data
